version: "3.8"

volumes:
  db:

services:
  db:
    container_name: iscc-registry-db
    image: postgres:14
    init: true
    environment:
      POSTGRES_USER: iscc
      POSTGRES_PASSWORD: generator
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: iscc-registry-redis
    image: redis:alpine
  app:
    container_name: iscc-registry-app
    init: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    build:
      target: dev-runtime
    environment:
      DEBUG: "true"
      DJANGO_SECRET_KEY: "set-to-secure-random-secret-in-production"
      DATABASE_URL: postgres://iscc:generator@db/iscc
      REDIS_URL: redis://redis/?db=1
      AUTO_MIGRATE_AND_INSTALL: "true"
    ports:
      - 127.0.0.1:8000:8000
  worker:
    container_name: iscc-registry-worker
    init: true
    depends_on:
      - db
      - redis
      - app
    volumes:
      - .:/app
    build:
      target: dev-runtime
    environment:
      DEBUG: "true"
      DJANGO_SECRET_KEY: "set-to-secure-random-secret-in-production"
      DATABASE_URL: postgres://iscc:generator@db/iscc
      REDIS_URL: redis://redis/?db=1
      AUTO_MIGRATE_AND_INSTALL: "false"
    command: dev/entrypoint-worker.sh
