version: "3.8"

volumes:
  db:

services:
  db:
    container_name: iscc-registry-db
    image: postgres:14
    init: true
    env_file:
      - .env.dev
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: iscc-registry-redis
    image: redis:alpine
  app:
    container_name: iscc-registry-app
    init: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    build:
      context: .
      target: dev-runtime
    env_file:
      - .env.dev
    environment:
      AUTO_MIGRATE_AND_INSTALL: "true"
    ports:
      - 127.0.0.1:8000:8000
  worker:
    container_name: iscc-registry-worker
    init: true
    depends_on:
      - db
      - redis
      - app
    volumes:
      - .:/app
    build:
      context: .
      target: dev-runtime
    env_file:
      - .env.dev
    environment:
      AUTO_MIGRATE_AND_INSTALL: "false"
    command: dev/entrypoint-worker.sh
