version: "3.8"

volumes:
  db:
  caddy-config:
  caddy-data:

services:
  db:
    container_name: iscc-registry-db
    image: postgres:14
    init: true
    env_file:
      - .env.dev
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    container_name: iscc-registry-redis
    image: redis:alpine
  app:
    container_name: iscc-registry-app
    init: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    build:
      context: .
      target: dev-runtime
    env_file:
      - .env.dev
    environment:
      AUTO_MIGRATE_AND_INSTALL: "true"
    ports:
      - 127.0.0.1:8000:8000
  worker:
    container_name: iscc-registry-worker
    init: true
    depends_on:
      - db
      - redis
      - app
    volumes:
      - .:/app
    build:
      context: .
      target: dev-runtime
    env_file:
      - .env.dev
    environment:
      AUTO_MIGRATE_AND_INSTALL: "false"
    command: dev/entrypoint-worker.sh
  caddy:
    container_name: iscc-registry-caddy
    image: "caddy:2.4.6-alpine"
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # configuration
      - caddy-config:/config  # configuation autosaves
      - caddy-data:/data  # saving certificates
    ports:
      - "8888:8888"
    depends_on:
      - db
      - redis
      - app
      - worker
