name: Tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13

      - name: Install Project
        run: |
          poetry install
          poetry run python manage.py makemigrations
          poetry run python manage.oy migrate

      - name: Run Tests
        run: poetry run pytest
